apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: homepage-ui
  name: homepage-ui
  namespace: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      run: homepage-ui
  template:
    metadata:
      labels:
        run: homepage-ui
    spec:
      containers:
        - name: homepage-ui
          image: ninepiece2/homepage:ui
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_BASE_URL
              value: "http://homepage-api-service:8080"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-api
  namespace: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: homepage-api
  template:
    metadata:
      labels:
        app: homepage-api
    spec:
      containers:
        - name: homepage-api
          image: ninepiece2/homepage:api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://*:8080"

---

apiVersion: v1
kind: Service
metadata:
  name: homepage-ui-service
  namespace: homepage
spec:
  selector:
    run: homepage-ui
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: homepage-api-service
  namespace: homepage
spec:
  selector:
    app: homepage-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homepage-ui-hpa
  namespace: homepage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage-ui
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homepage-api-hpa
  namespace: homepage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70